/**
 * Builds supabase/seed.sql from the mock data in /data, so the live database
 * starts with exactly what you see in development.
 *
 *   node scripts/make-seed.mjs
 *
 * It compiles the TypeScript data files with the project's own TypeScript,
 * loads them, and writes plain INSERT statements. Safe to re-run: it
 * truncates the demo tables first.
 */
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { tmpdir } from "node:os";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const require = createRequire(import.meta.url);
const ts = require(join(root, "node_modules", "typescript"));

// 1. Compile /data/*.ts → a temp folder as CommonJS
const out = join(tmpdir(), "rego-seed");
mkdirSync(out, { recursive: true });
for (const f of readdirSync(join(root, "data")).filter((x) => x.endsWith(".ts"))) {
  const src = readFileSync(join(root, "data", f), "utf8").replace(/from "@\/data\//g, 'from "./');
  const js = ts.transpileModule(src, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText;
  writeFileSync(join(out, f.replace(/\.ts$/, ".js")), js);
}
const load = (n) => require(join(out, `${n}.js`));
const { districts } = load("locations");
const { categories } = load("categories");
const { bazaars } = load("bazaars");
const { sellers } = load("sellers");
const { me } = load("account");
const { shops } = load("shops");
const { shopProfiles, shopReviews } = load("shop-profiles");
const { listings } = load("listings");
const { wantedRequests } = load("wanted");

// 2. SQL helpers
const q = (v) => {
  if (v === undefined || v === null) return "null";
  if (typeof v === "boolean") return v ? "true" : "false";
  if (typeof v === "number") return String(v);
  return `'${String(v).replace(/'/g, "''")}'`;
};
const arr = (a) => (a && a.length ? `array[${a.map(q).join(", ")}]::text[]` : "'{}'::text[]");
const json = (o) => (o === undefined || o === null ? "null" : `${q(JSON.stringify(o))}::jsonb`);
const ago = (iso) => {
  const h = Math.max(0, Math.round((Date.now() - new Date(iso).getTime()) / 36e5));
  return `now() - interval '${h} hours'`;
};
const img = (m) => (m && m.src && /^https?:/.test(m.src) ? m.src : null);
const rows = (table, cols, list) =>
  list.length ? `insert into public.${table} (${cols.join(", ")}) values\n  ${list.map((r) => `(${r.join(", ")})`).join(",\n  ")};\n` : "";

const sql = [];
sql.push("-- Generated by scripts/make-seed.mjs — do not edit by hand.\nbegin;\nset constraints all deferred;\n");
sql.push(
  "truncate public.shop_reviews, public.wanted_offers, public.wanted_requests, public.listings, public.shops, public.seller_contacts, public.sellers, public.bazaars, public.categories, public.districts cascade;\n",
);

sql.push(rows("districts", ["slug", "name", "headquarters", "division", "sort"], districts.map((d, i) => [q(d.slug), q(d.name), q(d.headquarters), q(d.division), i])));
sql.push(
  rows(
    "categories",
    ["slug", "name", "short_name", "icon", "description", "image_url", "sort"],
    categories.map((c, i) => [q(c.slug), q(c.name), q(c.shortName), q(c.icon), q(c.description), q(img(c.image)), i]),
  ),
);
sql.push(
  rows(
    "bazaars",
    ["slug", "name", "district", "town", "description", "image_url", "highlights", "shop_count", "product_count", "new_today"],
    bazaars.map((b) => [q(b.slug), q(b.name), q(b.district), q(b.town), q(b.description), q(img(b.image)), arr(b.highlights), b.shopCount, b.productCount, b.newToday]),
  ),
);

// Demo sellers (no login). The preview user "me" is left out: real accounts come from sign-up.
sql.push(
  rows(
    "sellers",
    ["id", "type", "name", "shop_slug", "verifications", "member_since", "district", "tehsil", "town", "phone_masked", "whatsapp", "rating", "review_count", "response_time", "accepts_orders", "delivery", "deals"],
    sellers.map((s) => [
      q(s.id), q(s.type), q(s.name), q(s.shopSlug), arr(s.verifications), q(s.memberSince), q(s.place.district), q(s.place.tehsil), q(s.place.town),
      q(s.phoneMasked), q(Boolean(s.whatsapp)), q(s.rating), s.reviewCount ?? 0, q(s.responseTime), q(Boolean(s.acceptsOrders)), q(Boolean(s.delivery)), s.deals ?? 0,
    ]),
  ),
);

sql.push(
  rows(
    "shops",
    ["id", "slug", "seller_id", "name", "tagline", "category", "district", "tehsil", "town", "bazaar", "verifications", "rating", "review_count", "followers", "trade_mode", "delivery", "accepts_orders", "hours", "cover_url", "logo_url", "monogram", "about", "founded", "payments", "delivery_note", "highlights", "address", "status"],
    shops.map((s) => {
      const p = shopProfiles[s.id] ?? {};
      return [
        q(s.id), q(s.slug), q(s.sellerId), q(s.name), q(s.tagline), q(s.category), q(s.place.district), q(s.place.tehsil), q(s.place.town), q(s.bazaar),
        arr(s.verifications), s.rating, s.reviewCount, s.followers, q(s.tradeMode), q(s.delivery), q(s.acceptsOrders), json(s.hours), q(img(s.cover)), q(img(s.logo)), q(s.monogram),
        arr(p.about), q(p.founded), arr(p.payments), q(p.deliveryNote ?? ""), arr(p.highlights), q(p.address ?? ""), q("active"),
      ];
    }),
  ),
);

const demoListings = listings.filter((l) => l.sellerId !== me.id);
sql.push(
  rows(
    "listings",
    ["id", "slug", "seller_id", "title", "category", "district", "tehsil", "town", "price", "unit", "negotiable", "images", "badges", "tag", "condition", "wholesale", "delivery", "livestock", "produce", "attributes", "views", "status", "posted_at"],
    demoListings.map((l) => [
      q(l.id), q(l.slug), q(l.sellerId), q(l.title), q(l.category), q(l.place.district), q(l.place.tehsil), q(l.place.town), l.price.amount, q(l.price.unit), q(Boolean(l.price.negotiable)),
      json(l.images.map((m) => ({ src: m.src, alt: m.alt }))), arr(l.badges), q(l.tag), q(l.condition), q(Boolean(l.wholesale)), q(Boolean(l.delivery)),
      json(l.livestock), json(l.produce), json(l.attributes), l.views, q("active"), ago(l.postedAt),
    ]),
  ),
);

sql.push(
  rows(
    "wanted_requests",
    ["id", "slug", "buyer_name", "buyer_type", "buyer_verified", "title", "category", "district", "town", "budget_min", "budget_max", "unit", "negotiable", "mode", "quantity", "details", "need_by", "offers", "posted_at"],
    wantedRequests.map((w) => [
      q(w.id), q(w.slug), q(w.buyerName), q(w.buyerType), q(w.buyerVerified), q(w.title), q(w.category), q(w.place.district), q(w.place.town),
      q(w.budget.min), q(w.budget.max), q(w.budget.unit), q(Boolean(w.budget.negotiable)), q(w.mode), q(w.quantity), q(w.details), q(w.needBy), w.offers, ago(w.postedAt),
    ]),
  ),
);

const slugs = new Set(demoListings.map((l) => l.slug));
sql.push(
  rows(
    "shop_reviews",
    ["id", "shop_id", "author", "from_place", "rating", "text", "item", "reply", "posted_at"],
    shopReviews.map((r) => [q(r.id), q(r.shopId), q(r.author), q(r.from), r.rating, q(r.text), q(r.item && slugs.has(r.item) ? r.item : null), q(r.reply), ago(r.postedAt)]),
  ),
);

sql.push("commit;\n");
const target = join(root, "supabase", "seed.sql");
writeFileSync(target, sql.join("\n"));
console.log(`Wrote ${target}: ${districts.length} districts, ${categories.length} categories, ${sellers.length} sellers, ${shops.length} shops, ${demoListings.length} listings, ${wantedRequests.length} wanted, ${shopReviews.length} reviews`);
